version: 2.1
    
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Installing Dependencies
          working_directory: ./frontend
          command: npm install
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Installing Dependencies
          working_directory: ./backend
          command: npm install
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  test-frontend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: frontend-build
      # Your job code here
      - run:
          name: Test front-end
          working_directory: ./frontend
          command: |
            npm test --ci --runInBand
                
  test-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: backend-build
      # Your job code here
      - run:
          name: Test Back-end
          working_directory: ./backend
          command: |
             npm test --ci --runInBand
  
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]