version: 2.1
    
jobs:
  backend-deps:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: npm install
          working_directory: ./backend
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - backend/node_modules


  frontend-deps:
    docker:
      - image: circleci/node:13.8.0
    steps:
        - checkout
        - run:
            name: npm install
            working_directory: ./frontend
            command: npm install
        - persist_to_workspace:
            root: .
            paths:
              - frontend/node_modules


  build-backend:
    docker:
      - image: circleci/node:13.8.0  
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: npm run build
          working_directory: ./backend
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - backend/dist


  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: npm run build
          working_directory: ./frontend
          command: npm run build


  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Front-End Tests
          working_directory: ./frontend
          command: npm test -- --ci --runInBand


  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Back-End Tests
          working_directory: ./backend
          command: npm test -- --ci --runInBand

workflows:
  default:
    jobs:
      - backend-deps
      - frontend-deps
      - build-backend:
          requires:
            - backend-deps
      - build-frontend:
          requires:
            - frontend-deps
      - test-backend:
          requires:
            - build-backend
      - test-frontend:
          requires:
            -  build-frontend